<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\CharacterClass;
use Illuminate\Database\Seeder;

final class ClassSeeder extends Seeder
{
    /**
     * @var array<array<string, mixed>>
     */
    private array $classes = [
        [
            'name'                       => 'Barbarian',
            'slug'                       => 'barbarian',
            'description'                => 'A fierce warrior who can enter a battle rage.',
            'hit_die'                    => 12,
            'primary_abilities'          => ['strength'],
            'saving_throw_proficiencies' => ['strength', 'constitution'],
            'armor_proficiencies'        => ['light', 'medium', 'shields'],
            'weapon_proficiencies'       => ['simple', 'martial'],
            'tool_proficiencies'         => [],
            'skill_choices'              => ['count' => 2, 'options' => ['animal-handling', 'athletics', 'intimidation', 'nature', 'perception', 'survival']],
            'starting_equipment'         => [],
            'spellcasting_ability'       => null,
            'subclass_level'             => 3,
        ],
        [
            'name'                       => 'Bard',
            'slug'                       => 'bard',
            'description'                => 'An inspiring magician whose power echoes the music of creation.',
            'hit_die'                    => 8,
            'primary_abilities'          => ['charisma'],
            'saving_throw_proficiencies' => ['dexterity', 'charisma'],
            'armor_proficiencies'        => ['light'],
            'weapon_proficiencies'       => ['simple', 'hand-crossbows', 'longswords', 'rapiers', 'shortswords'],
            'tool_proficiencies'         => ['musical-instruments'],
            'skill_choices'              => ['count' => 3, 'options' => ['acrobatics', 'animal-handling', 'arcana', 'athletics', 'deception', 'history', 'insight', 'intimidation', 'investigation', 'medicine', 'nature', 'perception', 'performance', 'persuasion', 'religion', 'sleight-of-hand', 'stealth', 'survival']],
            'starting_equipment'         => [],
            'spellcasting_ability'       => 'charisma',
            'subclass_level'             => 3,
        ],
        [
            'name'                       => 'Cleric',
            'slug'                       => 'cleric',
            'description'                => 'A priestly champion who wields divine magic in service of a higher power.',
            'hit_die'                    => 8,
            'primary_abilities'          => ['wisdom'],
            'saving_throw_proficiencies' => ['wisdom', 'charisma'],
            'armor_proficiencies'        => ['light', 'medium', 'shields'],
            'weapon_proficiencies'       => ['simple'],
            'tool_proficiencies'         => [],
            'skill_choices'              => ['count' => 2, 'options' => ['history', 'insight', 'medicine', 'persuasion', 'religion']],
            'starting_equipment'         => [],
            'spellcasting_ability'       => 'wisdom',
            'subclass_level'             => 1,
        ],
        [
            'name'                       => 'Druid',
            'slug'                       => 'druid',
            'description'                => 'A priest of the Old Faith, wielding the powers of nature.',
            'hit_die'                    => 8,
            'primary_abilities'          => ['wisdom'],
            'saving_throw_proficiencies' => ['intelligence', 'wisdom'],
            'armor_proficiencies'        => ['light', 'medium', 'shields'],
            'weapon_proficiencies'       => ['clubs', 'daggers', 'darts', 'javelins', 'maces', 'quarterstaffs', 'scimitars', 'sickles', 'slings', 'spears'],
            'tool_proficiencies'         => ['herbalism-kit'],
            'skill_choices'              => ['count' => 2, 'options' => ['arcana', 'animal-handling', 'insight', 'medicine', 'nature', 'perception', 'religion', 'survival']],
            'starting_equipment'         => [],
            'spellcasting_ability'       => 'wisdom',
            'subclass_level'             => 3,
        ],
        [
            'name'                       => 'Fighter',
            'slug'                       => 'fighter',
            'description'                => 'A master of martial combat, skilled with a variety of weapons and armor.',
            'hit_die'                    => 10,
            'primary_abilities'          => ['strength', 'dexterity'],
            'saving_throw_proficiencies' => ['strength', 'constitution'],
            'armor_proficiencies'        => ['light', 'medium', 'heavy', 'shields'],
            'weapon_proficiencies'       => ['simple', 'martial'],
            'tool_proficiencies'         => [],
            'skill_choices'              => ['count' => 2, 'options' => ['acrobatics', 'animal-handling', 'athletics', 'history', 'insight', 'intimidation', 'perception', 'survival']],
            'starting_equipment'         => [],
            'spellcasting_ability'       => null,
            'subclass_level'             => 3,
        ],
        [
            'name'                       => 'Monk',
            'slug'                       => 'monk',
            'description'                => 'A master of martial arts, harnessing the power of body and soul.',
            'hit_die'                    => 8,
            'primary_abilities'          => ['dexterity', 'wisdom'],
            'saving_throw_proficiencies' => ['strength', 'dexterity'],
            'armor_proficiencies'        => [],
            'weapon_proficiencies'       => ['simple', 'shortswords'],
            'tool_proficiencies'         => ['artisans-tools'],
            'skill_choices'              => ['count' => 2, 'options' => ['acrobatics', 'athletics', 'history', 'insight', 'religion', 'stealth']],
            'starting_equipment'         => [],
            'spellcasting_ability'       => null,
            'subclass_level'             => 3,
        ],
        [
            'name'                       => 'Paladin',
            'slug'                       => 'paladin',
            'description'                => 'A holy warrior bound to a sacred oath.',
            'hit_die'                    => 10,
            'primary_abilities'          => ['strength', 'charisma'],
            'saving_throw_proficiencies' => ['wisdom', 'charisma'],
            'armor_proficiencies'        => ['light', 'medium', 'heavy', 'shields'],
            'weapon_proficiencies'       => ['simple', 'martial'],
            'tool_proficiencies'         => [],
            'skill_choices'              => ['count' => 2, 'options' => ['athletics', 'insight', 'intimidation', 'medicine', 'persuasion', 'religion']],
            'starting_equipment'         => [],
            'spellcasting_ability'       => 'charisma',
            'subclass_level'             => 3,
        ],
        [
            'name'                       => 'Ranger',
            'slug'                       => 'ranger',
            'description'                => 'A warrior who combats threats on the edges of civilization.',
            'hit_die'                    => 10,
            'primary_abilities'          => ['dexterity', 'wisdom'],
            'saving_throw_proficiencies' => ['strength', 'dexterity'],
            'armor_proficiencies'        => ['light', 'medium', 'shields'],
            'weapon_proficiencies'       => ['simple', 'martial'],
            'tool_proficiencies'         => [],
            'skill_choices'              => ['count' => 3, 'options' => ['animal-handling', 'athletics', 'insight', 'investigation', 'nature', 'perception', 'stealth', 'survival']],
            'starting_equipment'         => [],
            'spellcasting_ability'       => 'wisdom',
            'subclass_level'             => 3,
        ],
        [
            'name'                       => 'Rogue',
            'slug'                       => 'rogue',
            'description'                => 'A scoundrel who uses stealth and trickery to overcome obstacles.',
            'hit_die'                    => 8,
            'primary_abilities'          => ['dexterity'],
            'saving_throw_proficiencies' => ['dexterity', 'intelligence'],
            'armor_proficiencies'        => ['light'],
            'weapon_proficiencies'       => ['simple', 'hand-crossbows', 'longswords', 'rapiers', 'shortswords'],
            'tool_proficiencies'         => ['thieves-tools'],
            'skill_choices'              => ['count' => 4, 'options' => ['acrobatics', 'athletics', 'deception', 'insight', 'intimidation', 'investigation', 'perception', 'performance', 'persuasion', 'sleight-of-hand', 'stealth']],
            'starting_equipment'         => [],
            'spellcasting_ability'       => null,
            'subclass_level'             => 3,
        ],
        [
            'name'                       => 'Sorcerer',
            'slug'                       => 'sorcerer',
            'description'                => 'A spellcaster who draws on inherent magic from a gift or bloodline.',
            'hit_die'                    => 6,
            'primary_abilities'          => ['charisma'],
            'saving_throw_proficiencies' => ['constitution', 'charisma'],
            'armor_proficiencies'        => [],
            'weapon_proficiencies'       => ['daggers', 'darts', 'slings', 'quarterstaffs', 'light-crossbows'],
            'tool_proficiencies'         => [],
            'skill_choices'              => ['count' => 2, 'options' => ['arcana', 'deception', 'insight', 'intimidation', 'persuasion']],
            'starting_equipment'         => [],
            'spellcasting_ability'       => 'charisma',
            'subclass_level'             => 1,
        ],
        [
            'name'                       => 'Warlock',
            'slug'                       => 'warlock',
            'description'                => 'A wielder of magic derived from a bargain with an extraplanar entity.',
            'hit_die'                    => 8,
            'primary_abilities'          => ['charisma'],
            'saving_throw_proficiencies' => ['wisdom', 'charisma'],
            'armor_proficiencies'        => ['light'],
            'weapon_proficiencies'       => ['simple'],
            'tool_proficiencies'         => [],
            'skill_choices'              => ['count' => 2, 'options' => ['arcana', 'deception', 'history', 'intimidation', 'investigation', 'nature', 'religion']],
            'starting_equipment'         => [],
            'spellcasting_ability'       => 'charisma',
            'subclass_level'             => 1,
        ],
        [
            'name'                       => 'Wizard',
            'slug'                       => 'wizard',
            'description'                => 'A scholarly magic-user capable of manipulating the structures of reality.',
            'hit_die'                    => 6,
            'primary_abilities'          => ['intelligence'],
            'saving_throw_proficiencies' => ['intelligence', 'wisdom'],
            'armor_proficiencies'        => [],
            'weapon_proficiencies'       => ['daggers', 'darts', 'slings', 'quarterstaffs', 'light-crossbows'],
            'tool_proficiencies'         => [],
            'skill_choices'              => ['count' => 2, 'options' => ['arcana', 'history', 'insight', 'investigation', 'medicine', 'religion']],
            'starting_equipment'         => [],
            'spellcasting_ability'       => 'intelligence',
            'subclass_level'             => 3,
        ],
    ];

    public function run(): void
    {
        foreach ($this->classes as $class) {
            CharacterClass::updateOrCreate(
                ['slug' => $class['slug']],
                $class
            );
        }
    }
}
