<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\Equipment;
use Illuminate\Database\Seeder;

final class EquipmentSeeder extends Seeder
{
    public function run(): void
    {
        $equipment = $this->getEquipmentData();

        foreach ($equipment as $item) {
            Equipment::create($item);
        }
    }

    /**
     * @return array<int, array<string, mixed>>
     */
    private function getEquipmentData(): array
    {
        return [
            // Simple Melee Weapons
            [
                'name' => 'Club',
                'type' => 'Weapon',
                'description' => 'A simple wooden club.',
                'cost_copper' => 10,
                'weight' => 2.00,
                'properties' => null,
                'weapon_properties' => [
                    'category' => 'simple_melee',
                    'damage' => '1d4',
                    'damage_type' => 'bludgeoning',
                    'properties' => ['light'],
                ],
                'armor_properties' => null,
                'requires_attunement' => false,
            ],
            [
                'name' => 'Dagger',
                'type' => 'Weapon',
                'description' => 'A simple dagger.',
                'cost_copper' => 200,
                'weight' => 1.00,
                'properties' => null,
                'weapon_properties' => [
                    'category' => 'simple_melee',
                    'damage' => '1d4',
                    'damage_type' => 'piercing',
                    'properties' => ['finesse', 'light', 'thrown'],
                    'range' => '20/60',
                ],
                'armor_properties' => null,
                'requires_attunement' => false,
            ],
            [
                'name' => 'Greatclub',
                'type' => 'Weapon',
                'description' => 'A large wooden club.',
                'cost_copper' => 20,
                'weight' => 10.00,
                'properties' => null,
                'weapon_properties' => [
                    'category' => 'simple_melee',
                    'damage' => '1d8',
                    'damage_type' => 'bludgeoning',
                    'properties' => ['two-handed'],
                ],
                'armor_properties' => null,
                'requires_attunement' => false,
            ],
            [
                'name' => 'Handaxe',
                'type' => 'Weapon',
                'description' => 'A simple hand axe.',
                'cost_copper' => 500,
                'weight' => 2.00,
                'properties' => null,
                'weapon_properties' => [
                    'category' => 'simple_melee',
                    'damage' => '1d6',
                    'damage_type' => 'slashing',
                    'properties' => ['light', 'thrown'],
                    'range' => '20/60',
                ],
                'armor_properties' => null,
                'requires_attunement' => false,
            ],
            [
                'name' => 'Javelin',
                'type' => 'Weapon',
                'description' => 'A throwing spear.',
                'cost_copper' => 50,
                'weight' => 2.00,
                'properties' => null,
                'weapon_properties' => [
                    'category' => 'simple_melee',
                    'damage' => '1d6',
                    'damage_type' => 'piercing',
                    'properties' => ['thrown'],
                    'range' => '30/120',
                ],
                'armor_properties' => null,
                'requires_attunement' => false,
            ],
            [
                'name' => 'Mace',
                'type' => 'Weapon',
                'description' => 'A simple mace.',
                'cost_copper' => 500,
                'weight' => 4.00,
                'properties' => null,
                'weapon_properties' => [
                    'category' => 'simple_melee',
                    'damage' => '1d6',
                    'damage_type' => 'bludgeoning',
                    'properties' => [],
                ],
                'armor_properties' => null,
                'requires_attunement' => false,
            ],
            [
                'name' => 'Quarterstaff',
                'type' => 'Weapon',
                'description' => 'A simple wooden staff.',
                'cost_copper' => 20,
                'weight' => 4.00,
                'properties' => null,
                'weapon_properties' => [
                    'category' => 'simple_melee',
                    'damage' => '1d6',
                    'damage_type' => 'bludgeoning',
                    'properties' => ['versatile'],
                    'versatile_damage' => '1d8',
                ],
                'armor_properties' => null,
                'requires_attunement' => false,
            ],
            [
                'name' => 'Spear',
                'type' => 'Weapon',
                'description' => 'A simple spear.',
                'cost_copper' => 100,
                'weight' => 3.00,
                'properties' => null,
                'weapon_properties' => [
                    'category' => 'simple_melee',
                    'damage' => '1d6',
                    'damage_type' => 'piercing',
                    'properties' => ['thrown', 'versatile'],
                    'range' => '20/60',
                    'versatile_damage' => '1d8',
                ],
                'armor_properties' => null,
                'requires_attunement' => false,
            ],
            // Martial Melee Weapons
            [
                'name' => 'Battleaxe',
                'type' => 'Weapon',
                'description' => 'A martial battle axe.',
                'cost_copper' => 1000,
                'weight' => 4.00,
                'properties' => null,
                'weapon_properties' => [
                    'category' => 'martial_melee',
                    'damage' => '1d8',
                    'damage_type' => 'slashing',
                    'properties' => ['versatile'],
                    'versatile_damage' => '1d10',
                ],
                'armor_properties' => null,
                'requires_attunement' => false,
            ],
            [
                'name' => 'Longsword',
                'type' => 'Weapon',
                'description' => 'A martial longsword.',
                'cost_copper' => 1500,
                'weight' => 3.00,
                'properties' => null,
                'weapon_properties' => [
                    'category' => 'martial_melee',
                    'damage' => '1d8',
                    'damage_type' => 'slashing',
                    'properties' => ['versatile'],
                    'versatile_damage' => '1d10',
                ],
                'armor_properties' => null,
                'requires_attunement' => false,
            ],
            [
                'name' => 'Greatsword',
                'type' => 'Weapon',
                'description' => 'A large two-handed sword.',
                'cost_copper' => 5000,
                'weight' => 6.00,
                'properties' => null,
                'weapon_properties' => [
                    'category' => 'martial_melee',
                    'damage' => '2d6',
                    'damage_type' => 'slashing',
                    'properties' => ['heavy', 'two-handed'],
                ],
                'armor_properties' => null,
                'requires_attunement' => false,
            ],
            [
                'name' => 'Rapier',
                'type' => 'Weapon',
                'description' => 'A martial rapier.',
                'cost_copper' => 2500,
                'weight' => 2.00,
                'properties' => null,
                'weapon_properties' => [
                    'category' => 'martial_melee',
                    'damage' => '1d8',
                    'damage_type' => 'piercing',
                    'properties' => ['finesse'],
                ],
                'armor_properties' => null,
                'requires_attunement' => false,
            ],
            [
                'name' => 'Shortsword',
                'type' => 'Weapon',
                'description' => 'A martial shortsword.',
                'cost_copper' => 1000,
                'weight' => 2.00,
                'properties' => null,
                'weapon_properties' => [
                    'category' => 'martial_melee',
                    'damage' => '1d6',
                    'damage_type' => 'piercing',
                    'properties' => ['finesse', 'light'],
                ],
                'armor_properties' => null,
                'requires_attunement' => false,
            ],
            // Simple Ranged Weapons
            [
                'name' => 'Light Crossbow',
                'type' => 'Weapon',
                'description' => 'A simple crossbow.',
                'cost_copper' => 2500,
                'weight' => 5.00,
                'properties' => null,
                'weapon_properties' => [
                    'category' => 'simple_ranged',
                    'damage' => '1d8',
                    'damage_type' => 'piercing',
                    'properties' => ['ammunition', 'loading', 'two-handed'],
                    'range' => '80/320',
                ],
                'armor_properties' => null,
                'requires_attunement' => false,
            ],
            [
                'name' => 'Shortbow',
                'type' => 'Weapon',
                'description' => 'A simple shortbow.',
                'cost_copper' => 2500,
                'weight' => 2.00,
                'properties' => null,
                'weapon_properties' => [
                    'category' => 'simple_ranged',
                    'damage' => '1d6',
                    'damage_type' => 'piercing',
                    'properties' => ['ammunition', 'two-handed'],
                    'range' => '80/320',
                ],
                'armor_properties' => null,
                'requires_attunement' => false,
            ],
            // Martial Ranged Weapons
            [
                'name' => 'Longbow',
                'type' => 'Weapon',
                'description' => 'A martial longbow.',
                'cost_copper' => 5000,
                'weight' => 2.00,
                'properties' => null,
                'weapon_properties' => [
                    'category' => 'martial_ranged',
                    'damage' => '1d8',
                    'damage_type' => 'piercing',
                    'properties' => ['ammunition', 'heavy', 'two-handed'],
                    'range' => '150/600',
                ],
                'armor_properties' => null,
                'requires_attunement' => false,
            ],
            // Light Armor
            [
                'name' => 'Padded Armor',
                'type' => 'Armor',
                'description' => 'Padded armor consists of quilted layers of cloth and batting.',
                'cost_copper' => 500,
                'weight' => 8.00,
                'properties' => null,
                'weapon_properties' => null,
                'armor_properties' => [
                    'category' => 'light',
                    'armor_class' => 11,
                    'modifier' => 'dex',
                    'stealth_disadvantage' => true,
                ],
                'requires_attunement' => false,
            ],
            [
                'name' => 'Leather Armor',
                'type' => 'Armor',
                'description' => 'The breastplate and shoulder protectors of this armor are made of leather that has been stiffened by being boiled in oil.',
                'cost_copper' => 1000,
                'weight' => 10.00,
                'properties' => null,
                'weapon_properties' => null,
                'armor_properties' => [
                    'category' => 'light',
                    'armor_class' => 11,
                    'modifier' => 'dex',
                    'stealth_disadvantage' => false,
                ],
                'requires_attunement' => false,
            ],
            [
                'name' => 'Studded Leather Armor',
                'type' => 'Armor',
                'description' => 'Made from tough but flexible leather, studded leather is reinforced with close-set rivets or spikes.',
                'cost_copper' => 4500,
                'weight' => 13.00,
                'properties' => null,
                'weapon_properties' => null,
                'armor_properties' => [
                    'category' => 'light',
                    'armor_class' => 12,
                    'modifier' => 'dex',
                    'stealth_disadvantage' => false,
                ],
                'requires_attunement' => false,
            ],
            // Medium Armor
            [
                'name' => 'Hide Armor',
                'type' => 'Armor',
                'description' => 'This crude armor consists of thick furs and pelts.',
                'cost_copper' => 1000,
                'weight' => 12.00,
                'properties' => null,
                'weapon_properties' => null,
                'armor_properties' => [
                    'category' => 'medium',
                    'armor_class' => 12,
                    'modifier' => 'dex',
                    'max_dex_bonus' => 2,
                    'stealth_disadvantage' => false,
                ],
                'requires_attunement' => false,
            ],
            [
                'name' => 'Chain Shirt',
                'type' => 'Armor',
                'description' => 'Made of interlocking metal rings, a chain shirt is worn between layers of clothing or leather.',
                'cost_copper' => 5000,
                'weight' => 20.00,
                'properties' => null,
                'weapon_properties' => null,
                'armor_properties' => [
                    'category' => 'medium',
                    'armor_class' => 13,
                    'modifier' => 'dex',
                    'max_dex_bonus' => 2,
                    'stealth_disadvantage' => false,
                ],
                'requires_attunement' => false,
            ],
            [
                'name' => 'Scale Mail',
                'type' => 'Armor',
                'description' => 'This armor consists of a coat and leggings of leather covered with overlapping pieces of metal.',
                'cost_copper' => 5000,
                'weight' => 45.00,
                'properties' => null,
                'weapon_properties' => null,
                'armor_properties' => [
                    'category' => 'medium',
                    'armor_class' => 14,
                    'modifier' => 'dex',
                    'max_dex_bonus' => 2,
                    'stealth_disadvantage' => true,
                ],
                'requires_attunement' => false,
            ],
            // Heavy Armor
            [
                'name' => 'Chain Mail',
                'type' => 'Armor',
                'description' => 'Made of interlocking metal rings, chain mail includes a layer of quilted fabric worn underneath the mail to prevent chafing.',
                'cost_copper' => 7500,
                'weight' => 55.00,
                'properties' => null,
                'weapon_properties' => null,
                'armor_properties' => [
                    'category' => 'heavy',
                    'armor_class' => 16,
                    'modifier' => null,
                    'stealth_disadvantage' => true,
                ],
                'requires_attunement' => false,
            ],
            [
                'name' => 'Plate Armor',
                'type' => 'Armor',
                'description' => 'Plate consists of shaped, interlocking metal plates to cover the entire body.',
                'cost_copper' => 150000,
                'weight' => 65.00,
                'properties' => null,
                'weapon_properties' => null,
                'armor_properties' => [
                    'category' => 'heavy',
                    'armor_class' => 18,
                    'modifier' => null,
                    'stealth_disadvantage' => true,
                ],
                'requires_attunement' => false,
            ],
            // Shield
            [
                'name' => 'Shield',
                'type' => 'Armor',
                'description' => 'A shield is made from wood or metal and is carried in one hand.',
                'cost_copper' => 1000,
                'weight' => 6.00,
                'properties' => null,
                'weapon_properties' => null,
                'armor_properties' => [
                    'category' => 'shield',
                    'armor_class' => 2,
                    'modifier' => null,
                    'stealth_disadvantage' => false,
                ],
                'requires_attunement' => false,
            ],
            // Adventuring Gear
            [
                'name' => 'Backpack',
                'type' => 'Adventuring Gear',
                'description' => 'A leather pack with one large pocket.',
                'cost_copper' => 200,
                'weight' => 5.00,
                'properties' => ['capacity' => '1 cubic foot / 30 pounds'],
                'weapon_properties' => null,
                'armor_properties' => null,
                'requires_attunement' => false,
            ],
            [
                'name' => 'Bedroll',
                'type' => 'Adventuring Gear',
                'description' => 'A bedroll consists of bedding and a blanket.',
                'cost_copper' => 100,
                'weight' => 7.00,
                'properties' => null,
                'weapon_properties' => null,
                'armor_properties' => null,
                'requires_attunement' => false,
            ],
            [
                'name' => 'Rope, Hempen (50 feet)',
                'type' => 'Adventuring Gear',
                'description' => 'Rope, whether made of hemp or silk, has 2 hit points and can be burst with a DC 17 Strength check.',
                'cost_copper' => 100,
                'weight' => 10.00,
                'properties' => null,
                'weapon_properties' => null,
                'armor_properties' => null,
                'requires_attunement' => false,
            ],
            [
                'name' => 'Torch',
                'type' => 'Adventuring Gear',
                'description' => 'A torch burns for 1 hour, providing bright light in a 20-foot radius and dim light for an additional 20 feet.',
                'cost_copper' => 1,
                'weight' => 1.00,
                'properties' => null,
                'weapon_properties' => null,
                'armor_properties' => null,
                'requires_attunement' => false,
            ],
            [
                'name' => 'Waterskin',
                'type' => 'Adventuring Gear',
                'description' => 'A waterskin can hold 4 pints of liquid.',
                'cost_copper' => 20,
                'weight' => 5.00,
                'properties' => null,
                'weapon_properties' => null,
                'armor_properties' => null,
                'requires_attunement' => false,
            ],
            [
                'name' => 'Rations (1 day)',
                'type' => 'Adventuring Gear',
                'description' => 'Rations consist of dry foods suitable for extended travel, including jerky, dried fruit, hardtack, and nuts.',
                'cost_copper' => 50,
                'weight' => 2.00,
                'properties' => null,
                'weapon_properties' => null,
                'armor_properties' => null,
                'requires_attunement' => false,
            ],
            // Tools
            [
                'name' => "Thieves' Tools",
                'type' => 'Tool',
                'description' => 'This set of tools includes a small file, a set of lock picks, a small mirror mounted on a metal handle, a set of narrow-bladed scissors, and a pair of pliers.',
                'cost_copper' => 2500,
                'weight' => 1.00,
                'properties' => null,
                'weapon_properties' => null,
                'armor_properties' => null,
                'requires_attunement' => false,
            ],
            [
                'name' => 'Herbalism Kit',
                'type' => 'Tool',
                'description' => 'This kit contains a variety of instruments such as clippers, mortar and pestle, and pouches and vials used by herbalists to create remedies and potions.',
                'cost_copper' => 500,
                'weight' => 3.00,
                'properties' => null,
                'weapon_properties' => null,
                'armor_properties' => null,
                'requires_attunement' => false,
            ],
        ];
    }
}
