<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\Spell;
use Illuminate\Database\Seeder;

final class SpellSeeder extends Seeder
{
    public function run(): void
    {
        $spells = $this->getSpellData();

        foreach ($spells as $spellData) {
            Spell::create($spellData);
        }
    }

    /**
     * @return array<int, array<string, mixed>>
     */
    private function getSpellData(): array
    {
        return [
            // Cantrips (Level 0)
            [
                'name' => 'Fire Bolt',
                'level' => 0,
                'school' => 'Evocation',
                'casting_time' => '1 action',
                'range' => '120 feet',
                'components' => ['V', 'S'],
                'duration' => 'Instantaneous',
                'concentration' => false,
                'ritual' => false,
                'description' => 'You hurl a mote of fire at a creature or object within range. Make a ranged spell attack against the target. On a hit, the target takes 1d10 fire damage. A flammable object hit by this spell ignites if it isn\'t being worn or carried.',
                'higher_levels' => 'This spell\'s damage increases by 1d10 when you reach 5th level (2d10), 11th level (3d10), and 17th level (4d10).',
            ],
            [
                'name' => 'Mage Hand',
                'level' => 0,
                'school' => 'Conjuration',
                'casting_time' => '1 action',
                'range' => '30 feet',
                'components' => ['V', 'S'],
                'duration' => '1 minute',
                'concentration' => false,
                'ritual' => false,
                'description' => 'A spectral, floating hand appears at a point you choose within range. The hand lasts for the duration or until you dismiss it as an action. The hand vanishes if it is ever more than 30 feet away from you or if you cast this spell again.',
                'higher_levels' => null,
            ],
            [
                'name' => 'Light',
                'level' => 0,
                'school' => 'Evocation',
                'casting_time' => '1 action',
                'range' => 'Touch',
                'components' => ['V', 'M'],
                'duration' => '1 hour',
                'concentration' => false,
                'ritual' => false,
                'description' => 'You touch one object that is no larger than 10 feet in any dimension. Until the spell ends, the object sheds bright light in a 20-foot radius and dim light for an additional 20 feet.',
                'higher_levels' => null,
            ],
            [
                'name' => 'Prestidigitation',
                'level' => 0,
                'school' => 'Transmutation',
                'casting_time' => '1 action',
                'range' => '10 feet',
                'components' => ['V', 'S'],
                'duration' => 'Up to 1 hour',
                'concentration' => false,
                'ritual' => false,
                'description' => 'This spell is a minor magical trick that novice spellcasters use for practice. You create one of several minor effects within range.',
                'higher_levels' => null,
            ],
            [
                'name' => 'Sacred Flame',
                'level' => 0,
                'school' => 'Evocation',
                'casting_time' => '1 action',
                'range' => '60 feet',
                'components' => ['V', 'S'],
                'duration' => 'Instantaneous',
                'concentration' => false,
                'ritual' => false,
                'description' => 'Flame-like radiance descends on a creature that you can see within range. The target must succeed on a Dexterity saving throw or take 1d8 radiant damage.',
                'higher_levels' => 'The spell\'s damage increases by 1d8 when you reach 5th level (2d8), 11th level (3d8), and 17th level (4d8).',
            ],
            [
                'name' => 'Guidance',
                'level' => 0,
                'school' => 'Divination',
                'casting_time' => '1 action',
                'range' => 'Touch',
                'components' => ['V', 'S'],
                'duration' => 'Concentration, up to 1 minute',
                'concentration' => true,
                'ritual' => false,
                'description' => 'You touch one willing creature. Once before the spell ends, the target can roll a d4 and add the number rolled to one ability check of its choice.',
                'higher_levels' => null,
            ],
            [
                'name' => 'Eldritch Blast',
                'level' => 0,
                'school' => 'Evocation',
                'casting_time' => '1 action',
                'range' => '120 feet',
                'components' => ['V', 'S'],
                'duration' => 'Instantaneous',
                'concentration' => false,
                'ritual' => false,
                'description' => 'A beam of crackling energy streaks toward a creature within range. Make a ranged spell attack against the target. On a hit, the target takes 1d10 force damage.',
                'higher_levels' => 'The spell creates more than one beam when you reach higher levels: two beams at 5th level, three beams at 11th level, and four beams at 17th level.',
            ],
            [
                'name' => 'Thorn Whip',
                'level' => 0,
                'school' => 'Transmutation',
                'casting_time' => '1 action',
                'range' => '30 feet',
                'components' => ['V', 'S', 'M'],
                'duration' => 'Instantaneous',
                'concentration' => false,
                'ritual' => false,
                'description' => 'You create a long, vine-like whip covered in thorns that lashes out at your command toward a creature in range. Make a melee spell attack against the target. If the attack hits, the creature takes 1d6 piercing damage.',
                'higher_levels' => 'This spell\'s damage increases by 1d6 when you reach 5th level (2d6), 11th level (3d6), and 17th level (4d6).',
            ],
            // 1st Level Spells
            [
                'name' => 'Magic Missile',
                'level' => 1,
                'school' => 'Evocation',
                'casting_time' => '1 action',
                'range' => '120 feet',
                'components' => ['V', 'S'],
                'duration' => 'Instantaneous',
                'concentration' => false,
                'ritual' => false,
                'description' => 'You create three glowing darts of magical force. Each dart hits a creature of your choice that you can see within range. A dart deals 1d4 + 1 force damage to its target. The darts all strike simultaneously.',
                'higher_levels' => 'When you cast this spell using a spell slot of 2nd level or higher, the spell creates one more dart for each slot level above 1st.',
            ],
            [
                'name' => 'Cure Wounds',
                'level' => 1,
                'school' => 'Evocation',
                'casting_time' => '1 action',
                'range' => 'Touch',
                'components' => ['V', 'S'],
                'duration' => 'Instantaneous',
                'concentration' => false,
                'ritual' => false,
                'description' => 'A creature you touch regains a number of hit points equal to 1d8 + your spellcasting ability modifier.',
                'higher_levels' => 'When you cast this spell using a spell slot of 2nd level or higher, the healing increases by 1d8 for each slot level above 1st.',
            ],
            [
                'name' => 'Shield',
                'level' => 1,
                'school' => 'Abjuration',
                'casting_time' => '1 reaction',
                'range' => 'Self',
                'components' => ['V', 'S'],
                'duration' => '1 round',
                'concentration' => false,
                'ritual' => false,
                'description' => 'An invisible barrier of magical force appears and protects you. Until the start of your next turn, you have a +5 bonus to AC, including against the triggering attack.',
                'higher_levels' => null,
            ],
            [
                'name' => 'Detect Magic',
                'level' => 1,
                'school' => 'Divination',
                'casting_time' => '1 action',
                'range' => 'Self',
                'components' => ['V', 'S'],
                'duration' => 'Concentration, up to 10 minutes',
                'concentration' => true,
                'ritual' => true,
                'description' => 'For the duration, you sense the presence of magic within 30 feet of you. If you sense magic in this way, you can use your action to see a faint aura around any visible creature or object in the area that bears magic.',
                'higher_levels' => null,
            ],
            [
                'name' => 'Burning Hands',
                'level' => 1,
                'school' => 'Evocation',
                'casting_time' => '1 action',
                'range' => 'Self (15-foot cone)',
                'components' => ['V', 'S'],
                'duration' => 'Instantaneous',
                'concentration' => false,
                'ritual' => false,
                'description' => 'As you hold your hands with thumbs touching and fingers spread, a thin sheet of flames shoots forth from your outstretched fingertips. Each creature in a 15-foot cone must make a Dexterity saving throw. A creature takes 3d6 fire damage on a failed save, or half as much damage on a successful one.',
                'higher_levels' => 'When you cast this spell using a spell slot of 2nd level or higher, the damage increases by 1d6 for each slot level above 1st.',
            ],
            [
                'name' => 'Bless',
                'level' => 1,
                'school' => 'Enchantment',
                'casting_time' => '1 action',
                'range' => '30 feet',
                'components' => ['V', 'S', 'M'],
                'duration' => 'Concentration, up to 1 minute',
                'concentration' => true,
                'ritual' => false,
                'description' => 'You bless up to three creatures of your choice within range. Whenever a target makes an attack roll or a saving throw before the spell ends, the target can roll a d4 and add the number rolled to the attack roll or saving throw.',
                'higher_levels' => 'When you cast this spell using a spell slot of 2nd level or higher, you can target one additional creature for each slot level above 1st.',
            ],
            [
                'name' => 'Healing Word',
                'level' => 1,
                'school' => 'Evocation',
                'casting_time' => '1 bonus action',
                'range' => '60 feet',
                'components' => ['V'],
                'duration' => 'Instantaneous',
                'concentration' => false,
                'ritual' => false,
                'description' => 'A creature of your choice that you can see within range regains hit points equal to 1d4 + your spellcasting ability modifier.',
                'higher_levels' => 'When you cast this spell using a spell slot of 2nd level or higher, the healing increases by 1d4 for each slot level above 1st.',
            ],
            // 2nd Level Spells
            [
                'name' => 'Scorching Ray',
                'level' => 2,
                'school' => 'Evocation',
                'casting_time' => '1 action',
                'range' => '120 feet',
                'components' => ['V', 'S'],
                'duration' => 'Instantaneous',
                'concentration' => false,
                'ritual' => false,
                'description' => 'You create three rays of fire and hurl them at targets within range. You can hurl them at one target or several. Make a ranged spell attack for each ray. On a hit, the target takes 2d6 fire damage.',
                'higher_levels' => 'When you cast this spell using a spell slot of 3rd level or higher, you create one additional ray for each slot level above 2nd.',
            ],
            [
                'name' => 'Hold Person',
                'level' => 2,
                'school' => 'Enchantment',
                'casting_time' => '1 action',
                'range' => '60 feet',
                'components' => ['V', 'S', 'M'],
                'duration' => 'Concentration, up to 1 minute',
                'concentration' => true,
                'ritual' => false,
                'description' => 'Choose a humanoid that you can see within range. The target must succeed on a Wisdom saving throw or be paralyzed for the duration. At the end of each of its turns, the target can make another Wisdom saving throw.',
                'higher_levels' => 'When you cast this spell using a spell slot of 3rd level or higher, you can target one additional humanoid for each slot level above 2nd.',
            ],
            [
                'name' => 'Spiritual Weapon',
                'level' => 2,
                'school' => 'Evocation',
                'casting_time' => '1 bonus action',
                'range' => '60 feet',
                'components' => ['V', 'S'],
                'duration' => '1 minute',
                'concentration' => false,
                'ritual' => false,
                'description' => 'You create a floating, spectral weapon within range that lasts for the duration or until you cast this spell again. When you cast the spell, you can make a melee spell attack against a creature within 5 feet of the weapon. On a hit, the target takes force damage equal to 1d8 + your spellcasting ability modifier.',
                'higher_levels' => 'When you cast this spell using a spell slot of 3rd level or higher, the damage increases by 1d8 for every two slot levels above 2nd.',
            ],
            [
                'name' => 'Lesser Restoration',
                'level' => 2,
                'school' => 'Abjuration',
                'casting_time' => '1 action',
                'range' => 'Touch',
                'components' => ['V', 'S'],
                'duration' => 'Instantaneous',
                'concentration' => false,
                'ritual' => false,
                'description' => 'You touch a creature and can end either one disease or one condition afflicting it. The condition can be blinded, deafened, paralyzed, or poisoned.',
                'higher_levels' => null,
            ],
            [
                'name' => 'Misty Step',
                'level' => 2,
                'school' => 'Conjuration',
                'casting_time' => '1 bonus action',
                'range' => 'Self',
                'components' => ['V'],
                'duration' => 'Instantaneous',
                'concentration' => false,
                'ritual' => false,
                'description' => 'Briefly surrounded by silvery mist, you teleport up to 30 feet to an unoccupied space that you can see.',
                'higher_levels' => null,
            ],
            [
                'name' => 'Invisibility',
                'level' => 2,
                'school' => 'Illusion',
                'casting_time' => '1 action',
                'range' => 'Touch',
                'components' => ['V', 'S', 'M'],
                'duration' => 'Concentration, up to 1 hour',
                'concentration' => true,
                'ritual' => false,
                'description' => 'A creature you touch becomes invisible until the spell ends. Anything the target is wearing or carrying is invisible as long as it is on the target\'s person. The spell ends for a target that attacks or casts a spell.',
                'higher_levels' => 'When you cast this spell using a spell slot of 3rd level or higher, you can target one additional creature for each slot level above 2nd.',
            ],
            // 3rd Level Spells
            [
                'name' => 'Fireball',
                'level' => 3,
                'school' => 'Evocation',
                'casting_time' => '1 action',
                'range' => '150 feet',
                'components' => ['V', 'S', 'M'],
                'duration' => 'Instantaneous',
                'concentration' => false,
                'ritual' => false,
                'description' => 'A bright streak flashes from your pointing finger to a point you choose within range and then blossoms with a low roar into an explosion of flame. Each creature in a 20-foot-radius sphere centered on that point must make a Dexterity saving throw. A target takes 8d6 fire damage on a failed save, or half as much damage on a successful one.',
                'higher_levels' => 'When you cast this spell using a spell slot of 4th level or higher, the damage increases by 1d6 for each slot level above 3rd.',
            ],
            [
                'name' => 'Lightning Bolt',
                'level' => 3,
                'school' => 'Evocation',
                'casting_time' => '1 action',
                'range' => 'Self (100-foot line)',
                'components' => ['V', 'S', 'M'],
                'duration' => 'Instantaneous',
                'concentration' => false,
                'ritual' => false,
                'description' => 'A stroke of lightning forming a line 100 feet long and 5 feet wide blasts out from you in a direction you choose. Each creature in the line must make a Dexterity saving throw. A creature takes 8d6 lightning damage on a failed save, or half as much damage on a successful one.',
                'higher_levels' => 'When you cast this spell using a spell slot of 4th level or higher, the damage increases by 1d6 for each slot level above 3rd.',
            ],
            [
                'name' => 'Counterspell',
                'level' => 3,
                'school' => 'Abjuration',
                'casting_time' => '1 reaction',
                'range' => '60 feet',
                'components' => ['S'],
                'duration' => 'Instantaneous',
                'concentration' => false,
                'ritual' => false,
                'description' => 'You attempt to interrupt a creature in the process of casting a spell. If the creature is casting a spell of 3rd level or lower, its spell fails and has no effect. If it is casting a spell of 4th level or higher, make an ability check using your spellcasting ability.',
                'higher_levels' => 'When you cast this spell using a spell slot of 4th level or higher, the interrupted spell has no effect if its level is less than or equal to the level of the spell slot you used.',
            ],
            [
                'name' => 'Dispel Magic',
                'level' => 3,
                'school' => 'Abjuration',
                'casting_time' => '1 action',
                'range' => '120 feet',
                'components' => ['V', 'S'],
                'duration' => 'Instantaneous',
                'concentration' => false,
                'ritual' => false,
                'description' => 'Choose one creature, object, or magical effect within range. Any spell of 3rd level or lower on the target ends. For each spell of 4th level or higher on the target, make an ability check using your spellcasting ability.',
                'higher_levels' => 'When you cast this spell using a spell slot of 4th level or higher, you automatically end the effects of a spell on the target if the spell\'s level is equal to or less than the level of the spell slot you used.',
            ],
            [
                'name' => 'Fly',
                'level' => 3,
                'school' => 'Transmutation',
                'casting_time' => '1 action',
                'range' => 'Touch',
                'components' => ['V', 'S', 'M'],
                'duration' => 'Concentration, up to 10 minutes',
                'concentration' => true,
                'ritual' => false,
                'description' => 'You touch a willing creature. The target gains a flying speed of 60 feet for the duration. When the spell ends, the target falls if it is still aloft, unless it can stop the fall.',
                'higher_levels' => 'When you cast this spell using a spell slot of 4th level or higher, you can target one additional creature for each slot level above 3rd.',
            ],
            [
                'name' => 'Revivify',
                'level' => 3,
                'school' => 'Necromancy',
                'casting_time' => '1 action',
                'range' => 'Touch',
                'components' => ['V', 'S', 'M'],
                'duration' => 'Instantaneous',
                'concentration' => false,
                'ritual' => false,
                'description' => 'You touch a creature that has died within the last minute. That creature returns to life with 1 hit point. This spell can\'t return to life a creature that has died of old age, nor can it restore any missing body parts.',
                'higher_levels' => null,
            ],
        ];
    }
}
