<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\Spell;
use Illuminate\Database\Seeder;

final class SpellSeeder extends Seeder
{
    /**
     * @var array<array<string, mixed>>
     */
    private array $spells = [
        // Cantrips (Level 0)
        [
            'name'                => 'Fire Bolt',
            'slug'                => 'fire-bolt',
            'description'         => 'You hurl a mote of fire at a creature or object within range. Make a ranged spell attack against the target. On a hit, the target takes 1d10 fire damage.',
            'level'               => 0,
            'school'              => 'evocation',
            'casting_time'        => '1 action',
            'range'               => '120 feet',
            'components_verbal'   => true,
            'components_somatic'  => true,
            'components_material' => null,
            'duration'            => 'Instantaneous',
            'concentration'       => false,
            'ritual'              => false,
            'higher_levels'       => 'The spell\'s damage increases by 1d10 when you reach 5th level (2d10), 11th level (3d10), and 17th level (4d10).',
        ],
        [
            'name'                => 'Light',
            'slug'                => 'light',
            'description'         => 'You touch one object that is no larger than 10 feet in any dimension. The object sheds bright light in a 20-foot radius and dim light for an additional 20 feet.',
            'level'               => 0,
            'school'              => 'evocation',
            'casting_time'        => '1 action',
            'range'               => 'Touch',
            'components_verbal'   => true,
            'components_somatic'  => false,
            'components_material' => 'A firefly or phosphorescent moss',
            'duration'            => '1 hour',
            'concentration'       => false,
            'ritual'              => false,
            'higher_levels'       => null,
        ],
        [
            'name'                => 'Mage Hand',
            'slug'                => 'mage-hand',
            'description'         => 'A spectral, floating hand appears at a point you choose within range. The hand can manipulate objects, open doors, or perform other simple tasks.',
            'level'               => 0,
            'school'              => 'conjuration',
            'casting_time'        => '1 action',
            'range'               => '30 feet',
            'components_verbal'   => true,
            'components_somatic'  => true,
            'components_material' => null,
            'duration'            => '1 minute',
            'concentration'       => false,
            'ritual'              => false,
            'higher_levels'       => null,
        ],
        [
            'name'                => 'Prestidigitation',
            'slug'                => 'prestidigitation',
            'description'         => 'This spell is a minor magical trick that novice spellcasters use for practice. You create one of several minor effects.',
            'level'               => 0,
            'school'              => 'transmutation',
            'casting_time'        => '1 action',
            'range'               => '10 feet',
            'components_verbal'   => true,
            'components_somatic'  => true,
            'components_material' => null,
            'duration'            => 'Up to 1 hour',
            'concentration'       => false,
            'ritual'              => false,
            'higher_levels'       => null,
        ],
        [
            'name'                => 'Sacred Flame',
            'slug'                => 'sacred-flame',
            'description'         => 'Flame-like radiance descends on a creature that you can see within range. The target must succeed on a Dexterity saving throw or take 1d8 radiant damage.',
            'level'               => 0,
            'school'              => 'evocation',
            'casting_time'        => '1 action',
            'range'               => '60 feet',
            'components_verbal'   => true,
            'components_somatic'  => true,
            'components_material' => null,
            'duration'            => 'Instantaneous',
            'concentration'       => false,
            'ritual'              => false,
            'higher_levels'       => 'The spell\'s damage increases by 1d8 when you reach 5th level (2d8), 11th level (3d8), and 17th level (4d8).',
        ],
        [
            'name'                => 'Minor Illusion',
            'slug'                => 'minor-illusion',
            'description'         => 'You create a sound or an image of an object within range that lasts for the duration.',
            'level'               => 0,
            'school'              => 'illusion',
            'casting_time'        => '1 action',
            'range'               => '30 feet',
            'components_verbal'   => false,
            'components_somatic'  => true,
            'components_material' => 'A bit of fleece',
            'duration'            => '1 minute',
            'concentration'       => false,
            'ritual'              => false,
            'higher_levels'       => null,
        ],
        // 1st Level Spells
        [
            'name'                => 'Magic Missile',
            'slug'                => 'magic-missile',
            'description'         => 'You create three glowing darts of magical force. Each dart hits a creature of your choice that you can see within range.',
            'level'               => 1,
            'school'              => 'evocation',
            'casting_time'        => '1 action',
            'range'               => '120 feet',
            'components_verbal'   => true,
            'components_somatic'  => true,
            'components_material' => null,
            'duration'            => 'Instantaneous',
            'concentration'       => false,
            'ritual'              => false,
            'higher_levels'       => 'When you cast this spell using a spell slot of 2nd level or higher, the spell creates one more dart for each slot level above 1st.',
        ],
        [
            'name'                => 'Shield',
            'slug'                => 'shield',
            'description'         => 'An invisible barrier of magical force appears and protects you. Until the start of your next turn, you have a +5 bonus to AC.',
            'level'               => 1,
            'school'              => 'abjuration',
            'casting_time'        => '1 reaction',
            'range'               => 'Self',
            'components_verbal'   => true,
            'components_somatic'  => true,
            'components_material' => null,
            'duration'            => '1 round',
            'concentration'       => false,
            'ritual'              => false,
            'higher_levels'       => null,
        ],
        [
            'name'                => 'Cure Wounds',
            'slug'                => 'cure-wounds',
            'description'         => 'A creature you touch regains a number of hit points equal to 1d8 + your spellcasting ability modifier.',
            'level'               => 1,
            'school'              => 'evocation',
            'casting_time'        => '1 action',
            'range'               => 'Touch',
            'components_verbal'   => true,
            'components_somatic'  => true,
            'components_material' => null,
            'duration'            => 'Instantaneous',
            'concentration'       => false,
            'ritual'              => false,
            'higher_levels'       => 'When you cast this spell using a spell slot of 2nd level or higher, the healing increases by 1d8 for each slot level above 1st.',
        ],
        [
            'name'                => 'Detect Magic',
            'slug'                => 'detect-magic',
            'description'         => 'For the duration, you sense the presence of magic within 30 feet of you.',
            'level'               => 1,
            'school'              => 'divination',
            'casting_time'        => '1 action',
            'range'               => 'Self',
            'components_verbal'   => true,
            'components_somatic'  => true,
            'components_material' => null,
            'duration'            => 'Concentration, up to 10 minutes',
            'concentration'       => true,
            'ritual'              => true,
            'higher_levels'       => null,
        ],
        [
            'name'                => 'Sleep',
            'slug'                => 'sleep',
            'description'         => 'This spell sends creatures into a magical slumber. Roll 5d8; the total is how many hit points of creatures this spell can affect.',
            'level'               => 1,
            'school'              => 'enchantment',
            'casting_time'        => '1 action',
            'range'               => '90 feet',
            'components_verbal'   => true,
            'components_somatic'  => true,
            'components_material' => 'A pinch of fine sand, rose petals, or a cricket',
            'duration'            => '1 minute',
            'concentration'       => false,
            'ritual'              => false,
            'higher_levels'       => 'When you cast this spell using a spell slot of 2nd level or higher, roll an additional 2d8 for each slot level above 1st.',
        ],
        [
            'name'                => 'Bless',
            'slug'                => 'bless',
            'description'         => 'You bless up to three creatures of your choice within range. Whenever a target makes an attack roll or saving throw before the spell ends, the target can roll a d4 and add the number rolled.',
            'level'               => 1,
            'school'              => 'enchantment',
            'casting_time'        => '1 action',
            'range'               => '30 feet',
            'components_verbal'   => true,
            'components_somatic'  => true,
            'components_material' => 'A sprinkling of holy water',
            'duration'            => 'Concentration, up to 1 minute',
            'concentration'       => true,
            'ritual'              => false,
            'higher_levels'       => 'When you cast this spell using a spell slot of 2nd level or higher, you can target one additional creature for each slot level above 1st.',
        ],
        // 2nd Level Spells
        [
            'name'                => 'Scorching Ray',
            'slug'                => 'scorching-ray',
            'description'         => 'You create three rays of fire and hurl them at targets within range. You can hurl them at one target or several.',
            'level'               => 2,
            'school'              => 'evocation',
            'casting_time'        => '1 action',
            'range'               => '120 feet',
            'components_verbal'   => true,
            'components_somatic'  => true,
            'components_material' => null,
            'duration'            => 'Instantaneous',
            'concentration'       => false,
            'ritual'              => false,
            'higher_levels'       => 'When you cast this spell using a spell slot of 3rd level or higher, you create one additional ray for each slot level above 2nd.',
        ],
        [
            'name'                => 'Hold Person',
            'slug'                => 'hold-person',
            'description'         => 'Choose a humanoid that you can see within range. The target must succeed on a Wisdom saving throw or be paralyzed for the duration.',
            'level'               => 2,
            'school'              => 'enchantment',
            'casting_time'        => '1 action',
            'range'               => '60 feet',
            'components_verbal'   => true,
            'components_somatic'  => true,
            'components_material' => 'A small, straight piece of iron',
            'duration'            => 'Concentration, up to 1 minute',
            'concentration'       => true,
            'ritual'              => false,
            'higher_levels'       => 'When you cast this spell using a spell slot of 3rd level or higher, you can target one additional humanoid for each slot level above 2nd.',
        ],
        [
            'name'                => 'Misty Step',
            'slug'                => 'misty-step',
            'description'         => 'Briefly surrounded by silvery mist, you teleport up to 30 feet to an unoccupied space that you can see.',
            'level'               => 2,
            'school'              => 'conjuration',
            'casting_time'        => '1 bonus action',
            'range'               => 'Self',
            'components_verbal'   => true,
            'components_somatic'  => false,
            'components_material' => null,
            'duration'            => 'Instantaneous',
            'concentration'       => false,
            'ritual'              => false,
            'higher_levels'       => null,
        ],
        // 3rd Level Spells
        [
            'name'                => 'Fireball',
            'slug'                => 'fireball',
            'description'         => 'A bright streak flashes from your pointing finger to a point you choose within range and then blossoms with a low roar into an explosion of flame.',
            'level'               => 3,
            'school'              => 'evocation',
            'casting_time'        => '1 action',
            'range'               => '150 feet',
            'components_verbal'   => true,
            'components_somatic'  => true,
            'components_material' => 'A tiny ball of bat guano and sulfur',
            'duration'            => 'Instantaneous',
            'concentration'       => false,
            'ritual'              => false,
            'higher_levels'       => 'When you cast this spell using a spell slot of 4th level or higher, the damage increases by 1d6 for each slot level above 3rd.',
        ],
        [
            'name'                => 'Lightning Bolt',
            'slug'                => 'lightning-bolt',
            'description'         => 'A stroke of lightning forming a line 100 feet long and 5 feet wide blasts out from you in a direction you choose.',
            'level'               => 3,
            'school'              => 'evocation',
            'casting_time'        => '1 action',
            'range'               => 'Self (100-foot line)',
            'components_verbal'   => true,
            'components_somatic'  => true,
            'components_material' => 'A bit of fur and a rod of amber, crystal, or glass',
            'duration'            => 'Instantaneous',
            'concentration'       => false,
            'ritual'              => false,
            'higher_levels'       => 'When you cast this spell using a spell slot of 4th level or higher, the damage increases by 1d6 for each slot level above 3rd.',
        ],
        [
            'name'                => 'Counterspell',
            'slug'                => 'counterspell',
            'description'         => 'You attempt to interrupt a creature in the process of casting a spell.',
            'level'               => 3,
            'school'              => 'abjuration',
            'casting_time'        => '1 reaction',
            'range'               => '60 feet',
            'components_verbal'   => false,
            'components_somatic'  => true,
            'components_material' => null,
            'duration'            => 'Instantaneous',
            'concentration'       => false,
            'ritual'              => false,
            'higher_levels'       => 'When you cast this spell using a spell slot of 4th level or higher, the interrupted spell has no effect if its level is less than or equal to the level of the spell slot you used.',
        ],
        [
            'name'                => 'Dispel Magic',
            'slug'                => 'dispel-magic',
            'description'         => 'Choose one creature, object, or magical effect within range. Any spell of 3rd level or lower on the target ends.',
            'level'               => 3,
            'school'              => 'abjuration',
            'casting_time'        => '1 action',
            'range'               => '120 feet',
            'components_verbal'   => true,
            'components_somatic'  => true,
            'components_material' => null,
            'duration'            => 'Instantaneous',
            'concentration'       => false,
            'ritual'              => false,
            'higher_levels'       => 'When you cast this spell using a spell slot of 4th level or higher, you automatically end the effects of a spell on the target if the spell\'s level is equal to or less than the level of the spell slot you used.',
        ],
        // 4th Level Spells
        [
            'name'                => 'Dimension Door',
            'slug'                => 'dimension-door',
            'description'         => 'You teleport yourself from your current location to any other spot within range.',
            'level'               => 4,
            'school'              => 'conjuration',
            'casting_time'        => '1 action',
            'range'               => '500 feet',
            'components_verbal'   => true,
            'components_somatic'  => false,
            'components_material' => null,
            'duration'            => 'Instantaneous',
            'concentration'       => false,
            'ritual'              => false,
            'higher_levels'       => null,
        ],
        [
            'name'                => 'Greater Invisibility',
            'slug'                => 'greater-invisibility',
            'description'         => 'You or a creature you touch becomes invisible until the spell ends. Anything the target is wearing or carrying is invisible as long as it is on the target\'s person.',
            'level'               => 4,
            'school'              => 'illusion',
            'casting_time'        => '1 action',
            'range'               => 'Touch',
            'components_verbal'   => true,
            'components_somatic'  => true,
            'components_material' => null,
            'duration'            => 'Concentration, up to 1 minute',
            'concentration'       => true,
            'ritual'              => false,
            'higher_levels'       => null,
        ],
        // 5th Level Spells
        [
            'name'                => 'Cone of Cold',
            'slug'                => 'cone-of-cold',
            'description'         => 'A blast of cold air erupts from your hands. Each creature in a 60-foot cone must make a Constitution saving throw.',
            'level'               => 5,
            'school'              => 'evocation',
            'casting_time'        => '1 action',
            'range'               => 'Self (60-foot cone)',
            'components_verbal'   => true,
            'components_somatic'  => true,
            'components_material' => 'A small crystal or glass cone',
            'duration'            => 'Instantaneous',
            'concentration'       => false,
            'ritual'              => false,
            'higher_levels'       => 'When you cast this spell using a spell slot of 6th level or higher, the damage increases by 1d8 for each slot level above 5th.',
        ],
        [
            'name'                => 'Wall of Force',
            'slug'                => 'wall-of-force',
            'description'         => 'An invisible wall of force springs into existence at a point you choose within range.',
            'level'               => 5,
            'school'              => 'evocation',
            'casting_time'        => '1 action',
            'range'               => '120 feet',
            'components_verbal'   => true,
            'components_somatic'  => true,
            'components_material' => 'A pinch of powder made by crushing a clear gemstone',
            'duration'            => 'Concentration, up to 10 minutes',
            'concentration'       => true,
            'ritual'              => false,
            'higher_levels'       => null,
        ],
    ];

    public function run(): void
    {
        foreach ($this->spells as $spell) {
            Spell::updateOrCreate(
                ['slug' => $spell['slug']],
                $spell
            );
        }
    }
}
